### ISSUE TITLE
ワンダーコア（オレンジ）

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#10]
## 5,000

ネタ用だったので、殆ど使っていません。
腹筋割りたいかたはどうぞ。

http://item.rakuten.co.jp/shopjapan/wdc/

![recommend_image3](https://cloud.githubusercontent.com/assets/1702483/13217449/c8c3faf8-d9a5-11e5-8a59-6e40dccbba4a.png)

![img_7315](https://cloud.githubusercontent.com/assets/1702483/13309790/30d579ea-dbc3-11e5-8e9a-9fc486d204cf.jpg)

**Comment by m-murakami** [comment]
これ買いま～す(´▽`)ノ
取りに行くのって、いつかの週末でも大丈夫ですか？

**Comment by ganezasan** [comment]
青森成田さんで一旦確保します。
