### ISSUE TITLE
ニトリワークチェア　肘付き

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#13]
## 2,000

意外としっかり座れます。
背もたれも硬さがあります。高さの調節ができます。

![img_7342](https://cloud.githubusercontent.com/assets/1702483/13309906/49ca3656-dbc4-11e5-8fed-425fdb93dc94.jpg)

![img_7343](https://cloud.githubusercontent.com/assets/1702483/13309907/58b2172e-dbc4-11e5-922a-a5b5c86b5d81.jpg)

**Comment by biatunky** [comment]
ほしいです！
取りに行きます！

**Comment by ghost** [comment]
@biatunky ありがとうございます！
いつ頃とりにきますかー？

**Comment by ganezasan** [comment]
一旦確定したのでクローズします。
