### ISSUE TITLE
AirMac Time Capsule 2TB

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#15]
## 20,000

正常に動きます。見た目もすごく綺麗です。
他に2台あるので、不要になりました。

http://www.apple.com/jp/airmac-time-capsule/

![img_7347](https://cloud.githubusercontent.com/assets/1702483/13310072/3c08e934-dbc6-11e5-9c16-79ca7769c2bc.jpg)
![img_7348](https://cloud.githubusercontent.com/assets/1702483/13310071/3c0897fe-dbc6-11e5-82f9-52c42f99bd70.jpg)
![img_7349](https://cloud.githubusercontent.com/assets/1702483/13310073/3c0b5246-dbc6-11e5-8fdd-98b55ddfcf66.jpg)
![img_7350](https://cloud.githubusercontent.com/assets/1702483/13310070/3c08a758-dbc6-11e5-968a-ed02dbb9143b.jpg)

**Comment by yagitoshiro** [comment]
買う！

**Comment by ghost** [comment]
@yagitoshiro ありがとうございます！
郵送で送ります！

**Comment by yagitoshiro** [comment]
Facebookのメッセージで支払い情報教えてください

**Comment by ganezasan** [comment]
わかりました！少々お待ちお
一旦確保するのでクローズします。
