### ISSUE TITLE
iPhone5S 16GB 白

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#16]
#15,000

多少汚れていますが、正常に動きます。
検証機として利用していました。

![img_7358](https://cloud.githubusercontent.com/assets/1702483/13310094/75aba280-dbc6-11e5-8081-185df8ee921d.jpg)
![img_7359](https://cloud.githubusercontent.com/assets/1702483/13310096/75ac4ee2-dbc6-11e5-9af4-1e21f9db5d55.jpg)
![img_7360](https://cloud.githubusercontent.com/assets/1702483/13310097/75ac7f66-dbc6-11e5-80c4-91d8d5581728.jpg)
![img_7361](https://cloud.githubusercontent.com/assets/1702483/13310095/75ac4ed8-dbc6-11e5-9e82-d2a0584ad2d4.jpg)
![img_7362](https://cloud.githubusercontent.com/assets/1702483/13310099/75add0c8-dbc6-11e5-971e-58db9944d550.jpg)
![img_7364](https://cloud.githubusercontent.com/assets/1702483/13310100/75cfbcf6-dbc6-11e5-8b6d-af42dfc73acd.jpg)

**Comment by isseium** [comment]
![](http://tiqav.com/5Dl.jpg)

**Comment by ganezasan** [comment]
売却します〜
