### ISSUE TITLE
iPad mini 32GB （白）

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#18]
## 20,000

ME280J/A

![img_7351](https://cloud.githubusercontent.com/assets/1702483/13310113/8aaa783c-dbc6-11e5-8cf2-f12c91ee7ff5.jpg)
![img_7352](https://cloud.githubusercontent.com/assets/1702483/13310110/8aa928f6-dbc6-11e5-836d-27983b0a9200.jpg)
![img_7353](https://cloud.githubusercontent.com/assets/1702483/13310115/8aac2dc6-dbc6-11e5-9f76-54d2127cb25f.jpg)
![img_7354](https://cloud.githubusercontent.com/assets/1702483/13310112/8aaa46b4-dbc6-11e5-9f89-8910ecdedc9c.jpg)
![img_7355](https://cloud.githubusercontent.com/assets/1702483/13310111/8aa9fe98-dbc6-11e5-9ef0-2979ac28edc8.jpg)
![img_7356](https://cloud.githubusercontent.com/assets/1702483/13310114/8aaaaf0a-dbc6-11e5-8fae-2661ce4b2488.jpg)
![img_7357](https://cloud.githubusercontent.com/assets/1702483/13310116/8acae734-dbc6-11e5-824d-b4f74e0af578.jpg)

**Comment by yamadagane** [comment]
はーい、欲しいです。子どもたち向けのワークショップなど考えているのでぜひ。

**Comment by ganezasan** [comment]
ありがとうございます。Facebookの方でご連絡いたします。
一旦確保するのでクローズいたします。
