### ISSUE TITLE
バランスボール（緑）

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#21]
## 500

ポンプ付き、空気もれ等はありません。

![img_7316](https://cloud.githubusercontent.com/assets/1702483/13310139/c422d988-dbc6-11e5-8f21-98dbe7d28481.jpg)

**Comment by m-murakami** [comment]
これも子供の遊び道具として買わせて頂きます(笑)。

**Comment by ganezasan** [comment]
一旦確定でクローズします。
