### ISSUE TITLE
BenQ 24インチワイド スタンダードモニター (Full HD/TNパネル/ブルーライト軽減) GL2460HM①

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#3]
## 10,000

ハイコストパフォーマンスを実現した 24型フルハイビジョン液晶ディスプレイ
PC作業や美しい映像視聴を、より快適に
目の疲れを軽減させるフリッカーフリー技術を搭載した、24型フリッカーフリーLED液晶ディスプレイ

http://www.amazon.co.jp/gp/product/B00DCGO2PS/ref=oh_aui_detailpage_o04_s03?ie=UTF8&psc=1

![img_7374](https://cloud.githubusercontent.com/assets/1702483/13310444/71e81a18-dbc9-11e5-86f0-451d9341c7cc.jpg)
![61xmkpzxwll _sl1114_](https://cloud.githubusercontent.com/assets/1702483/13216928/52e18dc6-d9a2-11e5-9086-eed3b8ba72be.jpg)
![616n16nag7l _sl1000_](https://cloud.githubusercontent.com/assets/1702483/13216905/2e441484-d9a2-11e5-854a-440a6f2e4a72.jpg)
![71mg13awkzl _sl1500_](https://cloud.githubusercontent.com/assets/1702483/13216909/363e7bf2-d9a2-11e5-815a-d87574173f93.jpg)
![71pkto86qel _sl1500_](https://cloud.githubusercontent.com/assets/1702483/13216911/379c38c2-d9a2-11e5-8c07-c16b697fcc72.jpg)

**Comment by ghost** [comment]
青森池田さんに確定したのでクローズします。
