### ISSUE TITLE
バナナのぬいぐるみ

### ISSUE THREAD

**Issue by ganezasan** [ganezasan/GithubEC#32]
## 0

枕代わりにいいと思います。
クッションビーズが入ったぬいぐるみです。

![img_7322](https://cloud.githubusercontent.com/assets/1702483/13309825/765f0e5e-dbc3-11e5-9825-c9f68acd246e.jpg)

**Comment by m-murakami** [comment]
子供用にもらおうかな(笑)。

**Comment by ganezasan** [comment]
一旦確定でクローズします。
