### ISSUE TITLE
Nexus5 白

### ISSUE THREAD

**Issue by ghost** [ganezasan/GithubEC#35]
## 5,000

https://store.google.com/product/nexus_5?playredirect=true&hl=ja&sku=nexus_5_white_16gb

![img_7375](https://cloud.githubusercontent.com/assets/14106855/13343689/60f9780e-dc92-11e5-88c9-08882520acea.jpg)
![img_7376](https://cloud.githubusercontent.com/assets/14106855/13343690/60faaa62-dc92-11e5-9a2e-674937276a27.jpg)

**Comment by isseium** [comment]
![](http://tiqav.com/5Dl.jpg)
